### PR TITLE
Update OCI-Provider implementation

### PR DESCRIPTION
**Pull request by spacedan**
Hello Mr. Rajeev, 
I took a pass at updating your branch implementation of the OCI Provider so we can work on getting #4061 merged.
Though I'm still having an error, I believe I've made some progress. 
File paths I personally edited:
Move OCI among valid providers from perfkitbenchmarker/providers/__init__.py
to perfkitbenchmarker/provider_info.py
Change imports and reference of provider to provider_info in oci_network.py, oci_virtual_machine.py, and oci/provider_info.py
Though there is still somethig missing as it relates to networks, 
Error I'm getting running tests:

2023-06-01 12:07:07,871 425ae158 MainThread memcached_memtier(1/1) ERROR    Exception running benchmark
Traceback (most recent call last):
  File "/home/dhuston/git/ampsight/PerfKitBenchmarker/perfkitbenchmarker/pkb.py", line 1028, in RunBenchmarkTask
    RunBenchmark(spec_for_run, collector)
  File "/home/dhuston/git/ampsight/PerfKitBenchmarker/perfkitbenchmarker/pkb.py", line 808, in RunBenchmark
    DoProvisionPhase(spec, detailed_timer)
  File "/home/dhuston/git/ampsight/PerfKitBenchmarker/perfkitbenchmarker/pkb.py", line 427, in DoProvisionPhase
    spec.ConstructVirtualMachines()
  File "/home/dhuston/git/ampsight/PerfKitBenchmarker/perfkitbenchmarker/benchmark_spec.py", line 568, in ConstructVirtualMachines
    vms = self.ConstructVirtualMachineGroup(group_name, group_spec)
  File "/home/dhuston/git/ampsight/PerfKitBenchmarker/perfkitbenchmarker/benchmark_spec.py", line 503, in ConstructVirtualMachineGroup
    vm = self._CreateVirtualMachine(group_spec.vm_spec, os_type, cloud)
  File "/home/dhuston/git/ampsight/PerfKitBenchmarker/perfkitbenchmarker/benchmark_spec.py", line 971, in _CreateVirtualMachine
    return vm_class(vm_spec)
  File "/home/dhuston/git/ampsight/PerfKitBenchmarker/perfkitbenchmarker/providers/oci/oci_virtual_machine.py", line 118, in __init__
    self.network = oci_network.OciNetwork.GetNetwork(self)
  File "/home/dhuston/git/ampsight/PerfKitBenchmarker/perfkitbenchmarker/network.py", line 204, in GetNetwork
    return cls.GetNetworkFromNetworkSpec(cls._GetNetworkSpecFromVm(vm))
  File "/home/dhuston/git/ampsight/PerfKitBenchmarker/perfkitbenchmarker/network.py", line 245, in GetNetworkFromNetworkSpec
    key = cls._GetKeyFromNetworkSpec(spec)
  File "/home/dhuston/git/ampsight/PerfKitBenchmarker/perfkitbenchmarker/network.py", line 187, in _GetKeyFromNetworkSpec
    if spec.subnet_name:
AttributeError: 'BaseNetworkSpec' object has no attribute 'subnet_name'

If you have some time to discuss, i'd be more than happy to set up a call. 
-danny

### CODE REVIEW

**Comment by spacedan** [comment]
It seems pkb now expects some specification of Subnets when creating networks, we may need to implement some differentiation of subnet objects as implemented in aws_network, azure_network, or gce_network

**Comment by gadgilrajeev** [comment]
@spacedan I was OOO last week so could not respond. We can setup some time this week. I am in India Time Zone so let me know what time works.

**Comment by spacedan** [comment]
@gadgilrajeev No worries! I’m currently working on bringing your changes up to date so we can get OCI merged! I’ll be OOO as well for a few days - Let’s meet next week, Wednesday June 14th if that works for you?

**Comment by gadgilrajeev** [comment]
@spacedan yes Wednesday 14th works for me. Please send me a meeting request.

**Comment by spacedan** [comment]
@gadgilrajeev - I've just push two things:
1. An update from Google's master branch of this repository
2. Work that we did on the oci_network and overall defaul network configs to implement the allow port method:
here:
https://github.com/gadgilrajeev/PerfKitBenchmarker/pull/1/commits/9ab62f9785def7b10fccc04324849974b1ccbed7
and here: 
https://github.com/gadgilrajeev/PerfKitBenchmarker/pull/1/commits/aabf476ad22ccf2777f8b1318fdb544a2fe81938
Please evaluate for yourself and ensure this is up to date with Google's master branch. 
-Danny

**Pull request merged**
